container:
  default: 'docker://bsmith89/compbio2:41cb510c9cbccc31155a6a79f44115d8eeb161cd'
  gtpro: 'docker://bsmith89/gtpro:87767c1292df1c04cd5cebde9e88aa418ab9b7fe'
  sfacts: 'docker://bsmith89/sfacts_dev:64dca4ffe0ad46f0b3b91ed00d4f5d81c92ef587'
  mambaforge: 'docker://condaforge/mambaforge:4.11.0-4'
proc: 'noop'
software-dev-path:
  sfacts: '/pollard/home/bsmith/Projects/StrainFacts'
MAX_THREADS: 4
USE_CUDA: 0
ALL:
  - data/core.a.r.proc.gtpro.filt-poly05-cvrg05.fit-sfacts2-s200-g10000-seed0.collapse-10.strain_depth.tsv
